# Workflow that makes a github release.
name: MakeGithubRelease

# Trigger the workflow when a new branch or a tag is created.
# There is no separate event for a creation of tag. But we choose to run the steps in this
# workflow only when the github ref was a tag.
on: create

jobs:
  trigger-build:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build.yml

  trigger-dfu-check:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/dfu_check.yml

  trigger-target-test:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/on_target.yml

  make-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    # Only make a release if the above jobs are passing
    needs: [trigger-target-test]
    env:
        CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
        - name: Download artifact
          uses: dawidd6/action-download-artifact@v5
          with:
            workflow: on_target.yml
            workflow_conclusion: success

        - name: Deploy release to github
          uses: softprops/action-gh-release@v1
          with:
            fail_on_unmatched_files: true
            files: |
              merged.hex
